name: proxies
description: A collection of proxy API wrappers.
version: 0.2.0
homepage: https://github.com/hacker1024/proxies

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.0
  convert: ^3.0.0
  crypto: ^3.0.0

dev_dependencies:
  lint: ^1.5.3
