name: proxies
description: A collection of proxy API wrappers.
version: 0.1.2
homepage: https://github.com/hacker1024/proxies

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  meta: ^1.2.3
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.2
